services:
    cloudflared:
        image: cloudflare/cloudflared:2025.7.0
        platform: linux/arm64 # for ARM64 architecture
        container_name: cloudflared
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
        environment:
            - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
        networks:
            - default
        env_file:
            - .env

    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:2025.7
        restart: unless-stopped
        volumes:
            - ${DISK_PATH}/Docker/homeassistant:/config
        environment:
            - TZ=${TZ}
        ports:
            - "8123:8123"
        privileged: true
        env_file:
            - .env

    sftpgo:
        image: drakkan/sftpgo:v2.6.6
        container_name: sftpgo
        restart: unless-stopped
        ports:
            - "6666:2022" #  SFTP port
            - "9998:8080" #  Web UI port
        volumes:
            - ${DISK_PATH}/Docker/sftpgo:/var/lib/sftpgo
            - ${DISK_PATH}/Docker/sftpgo/backups:/srv/sftpgo/backups
            - ${DISK_PATH}:/srv/sftpgo/data/${FTP_USER}
        environment:
            - SFTPGO_USER=${FTP_USER}
            - SFTPGO_PASSWORD=${FTP_PASSWORD}
        networks:
            - default
        env_file:
            - .env

    homebridge:
        image: homebridge/homebridge:latest
        restart: always
        network_mode: host
        volumes:
            - ${DISK_PATH}/Docker/homebridge:/homebridge
        environment:
            - TZ=${TZ}
        logging:
            driver: json-file
            options:
                max-size: "10mb"
                max-file: "1"
